version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Optional, expose for API access
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # 👈 Makes frontend available at http://<IP>/
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
