version: "3.8"

services:
  backend:
    image: bgin86/backend
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: bgin86/frontend
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    