version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    expose:
      - "5000"  # Internal only; no need to publish to host
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose to host at port 80 for public access
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
