version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    expose:
      - "5000" # Internal use only
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    expose:
      - "80" # Internal use only
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Only NGINX exposes port 80 to the world
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
