version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Optional: only needed if you want to access backend directly
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" # Expose React app on port 80 (public)
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
