on: push

jobs:
  build-container:
    name: Login to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Frontend Images
      run:  |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./Frontend
    - name: Push Frontend Images
      run:  |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend
    - name: Build Backend Images
      run:  |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend ./Backend
    - name: Push Backend Images
      run:  |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend        
    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USER }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        port:  22
