on: push

jobs:
  build-container:
    name: Login to DockerHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Images
      run:  | 
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend
        
