name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend ./backend
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/myapp
          docker-compose pull
          docker-compose up -d
